name: Deploy Svelte App with Bun

on:
  push:
    branches:
      - release # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest # or specify a version

      - name: Install dependencies
        run: bun install

      - name: Build Svelte app
        run: bun run build

      - name: Deploy to Ubuntu server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dist/*"
          target: "/var/www/html/ui/button"
          strip_components: 1
